package com.madi.smarttask.feature_auth.util

object AuthConstants {
    const val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
    const val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"
    const val ERROR_INVALID_CREDENTIAL = "ERROR_INVALID_CREDENTIAL"
    const val ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE"
    const val ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
    const val ERROR_TOO_MANY_REQUESTS = "ERROR_TOO_MANY_REQUESTS"
}
